version: "3.8"

services:
  tfg:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tfg/logs:/app/logs
      - ./tfg/output:/app/output
      - ./tfg/storage:/app/storage
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - OPENAI_EMBEDDING_MODEL_NAME=${OPENAI_EMBEDDING_MODEL_NAME}
      - CREWAI_STORAGE_DIR=/app/storage/
      - OUTPUT_DIR=/app/output/
      - CREW_NAME=tfg_answer_crew
    command: ["poetry", "run", "crewai", "run"]