subtasks:
  description: >
    Create subtasks from the main task {topic}.

  expected_output: >
    List with all the subtask necessary to solve the main task in json format.

  agent: master

experts:
  description: >
    Create a list of experts that are needed to complete the subtasks of {topic}. Indicate to which subtask is
    each expert assigned by using the task's name.
    
  expected_output: >
    List of experts in json format.

  agent: hhrr

workflow:
  description: >
    Choose a workflow that would result in the most efficient way to solve the main task {topic} taking into 
    account the subtasks and the experts needed to complete them, the have to be the same as the ones in the files. 
    Indicate the order of the tasks to complete in the workflow.
  
  expected_output: >
    Workflow of the experts in json format.

  agent: planner