character_development:
  description: Create detailed profiles for main and supporting characters.
  expected_output: No expected output provided.
create_an_outline:
  description: Structure the narrative arc, including exposition, rising action, climax,
    and falling action.
  expected_output: No expected output provided.
develop_a_story_concept:
  description: Define the core idea and themes of the story.
  expected_output: No expected output provided.
drafting_the_story:
  description: Write the initial draft based on the outline.
  expected_output: No expected output provided.
finalizing_and_formatting:
  description: Prepare the manuscript for publication or submission.
  expected_output: No expected output provided.
revising_and_editing:
  description: Polish the manuscript, focusing on language, grammar, and narrative
    coherence.
  expected_output: No expected output provided.
style_guide_development:
  description: Specify tone, voice, and stylistic elements (e.g., descriptive language,
    dialogue format).
  expected_output: No expected output provided.
