Brainstorming_Ideas:
  description: >
    Generate a list of ideas or themes for the story.
  expected_output: >
    A diverse collection of story ideas or themes.
Creating_Characters:
  description: >
    Develop the main and supporting characters with backstories, personalities, and motivations.
  expected_output: >
    Detailed character profiles.
Outlining_the_Plot:
  description: >
    Craft an outline of the main plot points and structure of the story.
  expected_output: >
    A clear plot outline with key events and turning points.
Setting_the_Scene:
  description: >
    Establish the setting where the story takes place, including time and location.
  expected_output: >
    Description of the story's setting.
Writing_the_First_Draft:
  description: >
    Compose the first version of the story, focusing on getting ideas down.
  expected_output: >
    Complete first draft of the story.
Revising_and_Editing:
  description: >
    Review and refine the draft for coherence, grammar, and style.
  expected_output: >
    Updated draft with revisions and corrections.
Finalizing_the_Manuscript:
  description: >
    Prepare the final version of the story for submission or publication.
  expected_output: >
    Polished final manuscript.