Research_Destinations:
  description: >
    {topic} Identify and gather information about potential vacation destinations, including attractions, accommodations, and travel requirements.
  expected_output: >
    A list of researched destinations with their key features and travel information.
Establish_Budget:
  description: >
    {topic} Determine the overall budget for the vacation, including transportation, accommodation, food, and activities.
  expected_output: >
    A detailed budget breakdown for the vacation.
Plan_Itinerary:
  description: >
    {topic} Create a day-by-day itinerary that outlines the planned activities and travel logistics for the vacation.
  expected_output: >
    A comprehensive itinerary detailing each day's activities and locations.
Book_Accommodations:
  description: >
    {topic} Make reservations for accommodations according to the planned itinerary, ensuring they meet the budget and preferences.
  expected_output: >
    Confirmed bookings for accommodations along with reservation details.
Arrange_Transportation:
  description: >
    {topic} Organize transportation to and from the destination and within the destination, including flights, car rentals, or public transport.
  expected_output: >
    A complete transportation plan including booking confirmations and schedules.